/**
 * External imports
 */
import * as _ from 'lodash';

/**
 * Local imports
 */
import {Action} from '../core/Action';
import {NotificationType} from '../vars';

/**
 * Interfaces
 */
export interface INotification {
    text: string;
    type: NotificationType;
    delay?: number;

    /**
     * Should be generated by action
     * to be able to remove notification by id
     */
    id?: string;
}

export class HideNotificationByTimeOut extends Action<string> {}

export class ShowNotification extends Action<INotification> {

    protected defaultDelay: number = 3500;

    constructor() {
        super();

        // TODO: create actor via DI
        this.actors.push(this.hideByTimeout.bind(this));
    }

    hideByTimeout() {
        setTimeout(() => {
            this.createAction<HideNotificationByTimeOut>(HideNotificationByTimeOut)
                .emit(this.payload.id);
        }, this.payload.delay || this.defaultDelay);
    }

    emit(payload: INotification) {
        payload.id = _.uniqueId('notification');
        return super.emit(payload);
    }
}
