interface INotification {
    text: string;
    type: number;
    delay?: number;

    /**
     * Should be generated by action
     * to be able to remove notification by id
     */
    id?: string;
}
